INSERT OR REPLACE INTO products (id, name, description, price_cents, category_slug, category_label, image_count, hero_image_url, badge, sort_order, is_active) VALUES
('art-deco-walnut-armchair', 'Art Deco Walnut Armchair', 'Circa 1925. Original upholstery with geometric sunburst motif. Minor wear consistent with age. Excellent structural condition.', 145000, 'furniture', 'Furniture', 4, 'assets/icons/home.svg', 'Featured', 0, 1),
('hudson-river-valley-oil', 'Hudson River Valley Oil, c.1890', 'Unsigned. Oil on canvas, 18×24". Autumn pastoral with river and foliage. Original gilded frame. Minor craquelure.', 320000, 'art', 'Fine Art', 4, 'assets/icons/image.svg', 'New', 1, 1),
('victorian-garnet-brooch-set', 'Victorian Garnet Brooch Set', 'Three-piece parure: brooch, earrings, pendant. Rose-cut Bohemian garnets in gilded brass settings. Circa 1870–1890.', 87500, 'jewellery', 'Jewellery', 4, 'assets/icons/award.svg', NULL, 2, 1),
('french-mantel-clock-ormolu', 'French Mantel Clock, Ormolu', 'Gilt bronze case with porcelain panels. Eight-day movement by Japy Frères, Paris. Circa 1860. Running order.', 210000, 'objects', 'Decorative Objects', 4, 'assets/icons/clock.svg', 'Rare', 3, 1),
('gilded-pier-mirror', 'Gilded Pier Mirror, c.1880', 'American Federal-style carved and gilded frame. Original glass with characteristic silvering loss. 48"×72" overall.', 280000, 'furniture', 'Furniture', 4, 'assets/icons/maximize-2.svg', NULL, 4, 1),
('audubon-folio-print', 'Audubon Folio Print, Original', 'Hand-coloured lithograph from "Birds of America," double elephant folio. Plate CCCXII — Great Blue Heron. Fine condition.', 450000, 'books', 'Books & Ephemera', 4, 'assets/icons/book.svg', 'New', 5, 1),
('chinese-export-porcelain-pair', 'Chinese Export Porcelain Pair', 'Famille rose vases, Qianlong period (18th c.). Figural reserves on turquoise ground. Both with minor rim restoration.', 560000, 'objects', 'Decorative Objects', 4, 'assets/icons/archive.svg', NULL, 6, 1),
('art-nouveau-enamel-pendant', 'Art Nouveau Enamel Pendant', 'Plique-à-jour enamel dragonfly on 14k gold chain. French, circa 1905. Stamped with French guarantee marks. Magnificent condition.', 195000, 'jewellery', 'Jewellery', 4, 'assets/icons/heart.svg', NULL, 7, 1),
('portrait-of-a-lady-1848', 'Portrait of a Lady, 1848', 'Attributed to Chester Harding school. Oil on canvas, 24×30". Half-length portrait with lace collar. Period frame.', 175000, 'art', 'Fine Art', 4, 'assets/icons/pen-tool.svg', NULL, 8, 1);

INSERT OR REPLACE INTO events (id, starts_on, month_key, date_month_label, date_day, date_year, title, location, schedule_text, event_type, lead, extras_json, tags_json, sort_order, is_active) VALUES
('harrington-collection', '2026-04-12', 'apr', 'Apr', 12, 2026, 'The Harrington Collection', 'Greenville, DE', '9am – 4pm · Sat & Sun', 'In-Person', 'A distinguished two-day sale from the estate of the late Eleanor Harrington, longtime Greenville resident and dedicated collector. Highlights include a full service of Georgian sterling silver, an extensive suite of botanical engravings, and an extraordinary Chippendale walnut secretary desk dated approximately 1780. Mid-Century glass, Orientalia, and a large library of first editions round out this exceptional offering.', '[{"label":"Parking & arrival","body":"Complimentary parking on the circular drive; additional street parking on a first-come basis. Please enter through the main foyer—signage will guide you to the dedicated sale rooms on the first and second floors."},{"label":"Payment & packing","body":"We accept cash, major credit cards, and approved checks with valid identification. Porter service is available for large furniture; bring blankets or moving supplies if you plan to take sizable pieces."},{"label":"House rules","body":"No large bags in the main salons; children are welcome under supervision. Numbers may be issued at opening on busy mornings—arrive early for the best selection of silver and smalls."}]', '["Silver","Furniture","Prints","Books","Glass"]', 0, 1),
('bellhaven-manor', '2026-04-26', 'apr', 'Apr', 26, 2026, 'Bellhaven Manor Dispersal', 'Kennett Square, PA', '10am – 3pm · Saturday only', 'In-Person', 'The contents of a meticulously kept 1920s manor house, furnished entirely in the Art Deco style its original owners loved. Expect custom-built ebonised case pieces, at least four signed Tiffany-style lamps, an extensive collection of vintage costume jewellery including signed pieces by Miriam Haskell and Coro, and an elegant 2,000-volume personal library spanning travel, natural history, and the decorative arts.', '[{"label":"Parking & arrival","body":"Park in the marked visitor bays along the west lawn. Follow the gravel path to the side entrance—this sale concentrates on the ground floor and lower gallery for easier flow."},{"label":"Payment & packing","body":"Cash, card, and bank check welcome. A volunteer desk can hold purchases while you continue browsing; jewellery cases are staffed at all times."},{"label":"House rules","body":"Single-day sale with continuous admission; no preview day. Flash photography in the lamp gallery is politely declined to protect iridescent finishes."}]', '["Art Deco","Jewellery","Lamps","Books"]', 1, 1),
('merriweather-estate', '2026-05-10', 'may', 'May', 10, 2026, 'The Merriweather Estate', 'Media, PA', '9am – 5pm · Sat & Sun', 'In-Person', 'Three generations of passionate collectors come together in this major two-day event. The Merriweather family amassed a formidable collection spanning Asian export porcelain from the 17th–19th centuries, a gallery of ancestor and landscape oil portraits, full Victorian parlour furniture suites in horsehair and mahogany, and a walled garden''s worth of cast-iron and limestone statuary. Not to be missed.', '[{"label":"Parking & arrival","body":"Shuttle carts run from overflow parking at the parish lot three blocks south on Saturday peak hours. Garden statuary may be viewed outdoors weather permitting—wear sensible footwear."},{"label":"Payment & packing","body":"We accept cash, card, and wire for high-value porcelain lots. Crating partners are on call Sunday afternoon for larger garden pieces."},{"label":"House rules","body":"Two full days; Sunday often sees the best availability on case furniture. Food and drink remain outside on the stone terrace."}]', '["Porcelain","Paintings","Victorian","Garden","Furniture"]', 2, 1),
('west-chester-collectors', '2026-05-24', 'may', 'May', 24, 2026, 'West Chester Collector''s Clearance', 'West Chester, PA', '9am – 3pm · Saturday only', 'In-Person', 'A focused single-day sale from the estate of a retired university professor with decades of focused collecting in maps, antiquarian books, scientific instruments, and vintage photography. Highlights include a folio of hand-coloured 18th-century maps, a collection of 19th-century stereographs, and an outstanding group of early astronomical instruments in original fitted cases.', '[{"label":"Parking & arrival","body":"Municipal garage two blocks east offers validated parking with any purchase over $100—ask at the registration desk. The sale occupies the town house library and upper study."},{"label":"Payment & packing","body":"Cash and card preferred for paper ephemera; personal checks accepted from established clients. Gloves are provided for handling loose atlas plates."},{"label":"House rules","body":"Compact, scholarly sale—please keep voices low in instrument rooms. No backpacks; lockers available in the hall."}]', '["Maps","Books","Scientific","Photography"]', 3, 1),
('ashford-park-preview', '2026-06-07', 'jun', 'Jun', 7, 2026, 'The Ashford Park Auction Preview', 'Wilmington, DE', '10am – 4pm · Preview Only', 'Preview Event', 'A special preview event for our summer auction partnership with Ashford Park Auction House. View items in person before online bidding opens on June 14th. Catalogue available at the door. Highlights include a documented Quaker furniture suite from Chester County, important Delaware silver, and a group of early Pennsylvania watercolours.', '[{"label":"Parking & arrival","body":"Valet and self-park lanes at the auction house main entrance. This is a preview day only—no sales transactions on site; staff can register you for absentee and online bidding."},{"label":"Catalogue & registration","body":"Printed catalogues while supplies last; digital copies scan at the lobby kiosks. Condition reports may be requested at the specialist desk for Delaware silver and furniture lots."},{"label":"House rules","body":"Touching of framed works is limited to staff assistance. Online bidding for this sale opens June 14, 2026—see Ashford Park''s site for real-time schedules."}]', '["Preview","Auction","Pennsylvania","Silver"]', 4, 1);
